run:
	stack run

test:
	stack test

testWatch:
	stack build --file-watch --test --test-arguments '--rerun --failure-report=TESTREPORT --rerun-all-on-success'

bench:
	stack bench --benchmark-arguments '--output=benchmark.html'
